#!/bin/bash

CLASSDIR="classes/main/pt/ist/ap/a8/Tests"

if [[ ! -d $CLASSDIR ]];then
  if [[ ! $(ant compile) -eq 0 ]];then
    echo "Some really big shit happen; Check output bro!"
    exit
  fi
fi  
count=0
testsRun=0
for i in $(ls $CLASSDIR | grep class  | rev | cut -c 6- | rev);do
  echo "Running test class $i"
  if [[ $(ant run -Darg0=$i) -eq 0 ]];then
    count=$((count+1))
  fi
  testsRun=$((testsRun+1))
done

echo "Tests are over. Project passed $count tests out of $testsRun"
  
