#!/bin/bash

#export CLASSPATH=$(pwd)/Tests/classes/*:$(pwd)/lib/javassist/javassist.jar:$(pwd)/classes/

#Change this to the basedir of your project
BASEDIR="$HOME/4ano/PAVA/projects/p1"


#This is retarded blame turii
export CLASSPATH="$BASEDIR/jkargs.jar:$BASEDIR/classes/:$BASEDIR/Tests/src/:$BASEDIR/Tests/classes:$BASEDIR/Tests/classes/:$BASEDIR/Tests/classes/*:$BASEDIR/classes/pt/ist/ap/a8:$BASEDIR/lib/javassist/javassist.jar"

ant clean &>/dev/null;ant compile &>/dev/null;ant testsCompile &>/dev/null

for i in $(ls Tests/classes/Test* | rev | cut -b 7- | rev|cut -b 15-);do echo "Going for $i"; java ist.meic.pa.KeyConstructors $i &>Tests/output/$i ;colordiff Tests/output/$i Tests/expected/out$(echo $i | cut -b 5-).txt ;done

exit 0;

  
